import { TagMetadata } from '../types/engine';

/**
 * Tag Registry
 *
 * Central registry of all tags used in the world generation system.
 * Based on analysis from tag-analysis.json with added governance rules,
 * relationships, and consolidation opportunities.
 */

export const tagRegistry: TagMetadata[] = [
  // LOCATION TAGS
  {
    tag: 'name:*',
    category: 'location',
    rarity: 'common',
    description: 'Dynamic tag indicating entity\'s origin location using slugified name',
    usageCount: 14,
    templates: ['family_expansion', 'hero_emergence', 'succession', 'mysterious_vanishing', 'guild_establishment', 'crisis_legislation', 'great_festival', 'ideology_emergence'],
    entityKinds: ['npc', 'location', 'faction', 'rules'],
    minUsage: 5,
    maxUsage: 50,
    relatedTags: ['colony', 'new'],
  },

  // STATUS TAGS
  {
    tag: 'second_generation',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks children created through family expansion',
    usageCount: 1,
    templates: ['family_expansion'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['family'],
  },
  {
    tag: 'recruit',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks newly recruited outlaws',
    usageCount: 1,
    templates: ['outlaw_recruitment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['criminal'],
  },
  {
    tag: 'emergent',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks heroes who emerged during troubled times',
    usageCount: 1,
    templates: ['hero_emergence'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['brave'],
  },
  {
    tag: 'successor',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks NPCs who succeeded previous leaders',
    usageCount: 1,
    templates: ['succession'],
    entityKinds: ['npc'],
    minUsage: 3,
  },
  {
    tag: 'splinter',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks factions that split from parent organizations',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['rebel'],
  },
  {
    tag: 'guild-founder',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks founding members of guilds',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['guild', 'trader'],
  },
  {
    tag: 'prophet',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks cult prophets',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['cultist', 'mystic', 'cult'],
  },
  {
    tag: 'new',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks newly founded colonies',
    usageCount: 1,
    templates: ['colony_founding'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['colony'],
  },
  {
    tag: 'bloom',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks krill bloom locations',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['krill', 'resource'],
  },
  {
    tag: 'innovation',
    category: 'status',
    rarity: 'rare',
    description: 'Marks innovative technological developments',
    usageCount: 2,
    templates: ['tech_innovation', 'tech_breakthrough'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['tech', 'technology'],
  },

  // TRAIT TAGS
  {
    tag: 'traditional',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks NPCs who uphold traditional values (Ising model trait +1)',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    consolidateInto: 'tradition',
    conflictingTags: ['radical', 'rebellious'],
  },
  {
    tag: 'radical',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks NPCs who embrace change (Ising model trait -1)',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    conflictingTags: ['traditional', 'tradition'],
  },
  {
    tag: 'talented',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks prodigy family members',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
  },
  {
    tag: 'rebellious',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks blacksheep family members',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['rebel'],
    conflictingTags: ['traditional', 'tradition'],
  },
  {
    tag: 'brave',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks brave heroes',
    usageCount: 1,
    templates: ['hero_emergence'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['emergent'],
  },
  {
    tag: 'rebel',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks rebellious NPCs who lead splinter movements',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['rebellious', 'splinter'],
  },
  {
    tag: 'charismatic',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks charismatic leaders',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['npc'],
    minUsage: 3,
  },
  {
    tag: 'mystic',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks mystically-inclined NPCs',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['npc'],
    minUsage: 3,
    consolidateInto: 'mystical',
    relatedTags: ['mystical', 'prophet', 'cultist'],
  },
  {
    tag: 'mysterious',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks mysterious phenomena',
    usageCount: 1,
    templates: ['anomaly_manifestation'],
    entityKinds: ['location'],
    minUsage: 3,
    consolidateInto: 'mystical',
    relatedTags: ['mystery', 'anomaly'],
  },

  // AFFILIATION TAGS
  {
    tag: 'criminal',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks NPCs involved in criminal activities',
    usageCount: 2,
    templates: ['outlaw_recruitment'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['recruit'],
  },
  {
    tag: 'family',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks members of extended family structures',
    usageCount: 2,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['second_generation'],
  },
  {
    tag: 'orca',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks orca raiders and their combat techniques',
    usageCount: 2,
    templates: ['orca_raider_arrival', 'orca_combat_technique'],
    entityKinds: ['npc', 'abilities'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['raider', 'external-threat', 'predator'],
  },
  {
    tag: 'external-threat',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks entities representing external threats',
    usageCount: 2,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['orca', 'raider', 'predator'],
  },
  {
    tag: 'guild',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks guild factions',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['trade', 'guild-founder', 'trader'],
  },
  {
    tag: 'cult',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks cult factions',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['cultist', 'prophet', 'mystical', 'secretive'],
  },
  {
    tag: 'cultist',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks cult followers',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['cult', 'prophet', 'mystic'],
  },
  {
    tag: 'external',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks techniques from external threats',
    usageCount: 1,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['orca', 'external-threat'],
  },

  // BEHAVIOR TAGS
  {
    tag: 'raider',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks raiding NPCs',
    usageCount: 1,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['orca', 'predator', 'external-threat'],
  },
  {
    tag: 'predator',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks predatory NPCs',
    usageCount: 1,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['raider', 'orca', 'external-threat'],
  },
  {
    tag: 'trader',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks trader NPCs',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['guild', 'guild-founder', 'merchant'],
  },
  {
    tag: 'secretive',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks secretive factions',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['cult', 'mystical'],
  },
  {
    tag: 'explorer',
    category: 'behavior',
    rarity: 'rare',
    description: 'Marks explorer NPCs who discover new locations',
    usageCount: 2,
    templates: ['krill_bloom_migration'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 15,
  },
  {
    tag: 'merchant',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks merchant NPCs',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['trader'],
  },
  {
    tag: 'offensive',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks offensive combat techniques',
    usageCount: 1,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['combat'],
  },

  // THEME TAGS
  {
    tag: 'mystery',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks locations or entities involved in mysterious disappearances',
    usageCount: 2,
    templates: ['mysterious_vanishing'],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['vanishing', 'mysterious', 'anomaly'],
  },
  {
    tag: 'vanishing',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks disappearance sites',
    usageCount: 1,
    templates: ['mysterious_vanishing'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['mystery'],
  },
  {
    tag: 'trade',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks trade-focused factions',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['guild', 'trader', 'merchant'],
  },
  {
    tag: 'mystical',
    category: 'theme',
    rarity: 'uncommon',
    description: 'Marks mystical entities and locations',
    usageCount: 5,
    templates: ['cult_formation', 'anomaly_manifestation', 'magic_discovery'],
    entityKinds: ['faction', 'location', 'abilities'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['magic', 'mystic', 'mysterious', 'anomaly'],
  },
  {
    tag: 'colony',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks colony locations',
    usageCount: 1,
    templates: ['colony_founding'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['new'],
  },
  {
    tag: 'anomaly',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks anomalous locations',
    usageCount: 1,
    templates: ['anomaly_manifestation'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['mystical', 'mysterious', 'mystery'],
  },
  {
    tag: 'krill',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks krill-related resources and NPCs',
    usageCount: 3,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location', 'npc'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['bloom', 'resource'],
  },
  {
    tag: 'resource',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks resource-rich locations',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['krill', 'bloom'],
  },
  {
    tag: 'tech',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks technological abilities',
    usageCount: 1,
    templates: ['tech_innovation'],
    entityKinds: ['abilities'],
    minUsage: 3,
    consolidateInto: 'technology',
    relatedTags: ['technology', 'innovation'],
  },
  {
    tag: 'magic',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks magical abilities',
    usageCount: 2,
    templates: ['magic_discovery'],
    entityKinds: ['abilities'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['mystical'],
    conflictingTags: ['technology', 'tech'],
  },
  {
    tag: 'technology',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks technological abilities',
    usageCount: 1,
    templates: ['tech_breakthrough'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['tech', 'innovation'],
    conflictingTags: ['magic', 'mystical'],
  },
  {
    tag: 'combat',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks combat-related abilities',
    usageCount: 2,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['offensive'],
  },
  {
    tag: 'crisis',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks crisis-driven legislation',
    usageCount: 1,
    templates: ['crisis_legislation'],
    entityKinds: ['rules'],
    minUsage: 3,
  },
  {
    tag: 'festival',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks festival celebrations',
    usageCount: 2,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['harvest', 'memorial', 'treaty', 'celestial'],
  },
  {
    tag: 'harvest',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks harvest festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'memorial',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks memorial festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'treaty',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks peace treaty festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'celestial',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks celestial celebration festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'ideology',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks ideological movements',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
  },
  {
    tag: 'militarism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks militaristic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['pacifism'],
  },
  {
    tag: 'pacifism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks pacifist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['militarism'],
  },
  {
    tag: 'unity',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks unity-focused ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['isolation'],
  },
  {
    tag: 'isolation',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks isolationist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['unity'],
  },
  {
    tag: 'equality',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks equality-focused ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['hierarchy'],
  },
  {
    tag: 'tradition',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks traditionalist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['radical'],
  },
  {
    tag: 'hierarchy',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks hierarchical ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['equality'],
  },
  {
    tag: 'rationalism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks rationalist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['mystical'],
  },
  {
    tag: 'asceticism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks ascetic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['hedonism'],
  },
  {
    tag: 'hedonism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks hedonistic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['asceticism'],
  },
];

/**
 * Helper function to get tag metadata by tag name
 */
export function getTagMetadata(tag: string): TagMetadata | undefined {
  // Handle dynamic location tags like "name:aurora-berg"
  if (tag.startsWith('name:')) {
    return tagRegistry.find(t => t.tag === 'name:*');
  }
  return tagRegistry.find(t => t.tag === tag);
}

/**
 * Helper function to get all tags in a category
 */
export function getTagsByCategory(category: TagMetadata['category']): TagMetadata[] {
  return tagRegistry.filter(t => t.category === category);
}

/**
 * Helper function to get consolidation suggestions
 */
export function getConsolidationSuggestions(): Array<{ from: string; to: string }> {
  return tagRegistry
    .filter(t => t.consolidateInto)
    .map(t => ({ from: t.tag, to: t.consolidateInto! }));
}

/**
 * Helper function to check if two tags conflict
 */
export function tagsConflict(tag1: string, tag2: string): boolean {
  const metadata1 = getTagMetadata(tag1);
  const metadata2 = getTagMetadata(tag2);

  if (!metadata1 || !metadata2) return false;

  return (metadata1.conflictingTags?.includes(tag2) ||
          metadata2.conflictingTags?.includes(tag1)) ?? false;
}

/**
 * Validate that an entity's tags don't have conflicts
 */
export function validateEntityTags(tags: string[]): { valid: boolean; conflicts: string[] } {
  const conflicts: string[] = [];

  for (let i = 0; i < tags.length; i++) {
    for (let j = i + 1; j < tags.length; j++) {
      if (tagsConflict(tags[i], tags[j])) {
        conflicts.push(`${tags[i]} conflicts with ${tags[j]}`);
      }
    }
  }

  return {
    valid: conflicts.length === 0,
    conflicts
  };
}

/**
 * Check if a tag is registered in the registry
 * (Backward compatibility export)
 */
export function isRegisteredTag(tag: string): boolean {
  return !!getTagMetadata(tag);
}

/**
 * Get tag definition/metadata by tag name
 * (Backward compatibility export - alias for getTagMetadata)
 */
export function getTagDefinition(tag: string): TagMetadata | undefined {
  return getTagMetadata(tag);
}
