/**
 * Penguin Domain Tag Registry
 *
 * Central registry of all tags used in the penguin world generation system.
 * Based on analysis from tag-analysis.json with added governance rules,
 * relationships, and consolidation opportunities.
 */

import type { TagMetadata } from '@lore-weave/core';

export const penguinTagRegistry: TagMetadata[] = [
  // STATUS TAGS
  {
    tag: 'second_generation',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks children created through family expansion',
    usageCount: 1,
    templates: ['family_expansion'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['family'],
  },
  {
    tag: 'recruit',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks newly recruited outlaws',
    usageCount: 1,
    templates: ['outlaw_recruitment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['criminal'],
  },
  {
    tag: 'emergent',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks heroes who emerged during troubled times',
    usageCount: 1,
    templates: ['hero_emergence'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['brave'],
  },
  {
    tag: 'successor',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks NPCs who succeeded previous leaders',
    usageCount: 1,
    templates: ['succession'],
    entityKinds: ['npc'],
    minUsage: 3,
  },
  {
    tag: 'splinter',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks factions that split from parent organizations',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['rebel'],
  },
  {
    tag: 'guild-founder',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks founding members of guilds',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['guild', 'trader'],
  },
  {
    tag: 'prophet',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks cult prophets',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['cultist', 'mystic', 'cult'],
  },
  {
    tag: 'new',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks newly founded colonies',
    usageCount: 1,
    templates: ['colony_founding'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['colony'],
  },
  {
    tag: 'bloom',
    category: 'status',
    rarity: 'legendary',
    description: 'Marks krill bloom locations',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['krill', 'resource'],
  },
  {
    tag: 'innovation',
    category: 'status',
    rarity: 'rare',
    description: 'Marks innovative technological developments',
    usageCount: 2,
    templates: ['tech_innovation', 'tech_breakthrough'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['tech', 'technology'],
  },

  // TRAIT TAGS
  {
    tag: 'traditional',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks NPCs who uphold traditional values (Ising model trait +1)',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    consolidateInto: 'tradition',
    conflictingTags: ['radical', 'rebellious'],
  },
  {
    tag: 'radical',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks NPCs who embrace change (Ising model trait -1)',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    conflictingTags: ['traditional', 'tradition'],
  },
  {
    tag: 'talented',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks prodigy family members',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
  },
  {
    tag: 'rebellious',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks blacksheep family members',
    usageCount: 1,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['rebel'],
    conflictingTags: ['traditional', 'tradition'],
  },
  {
    tag: 'brave',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks brave heroes',
    usageCount: 1,
    templates: ['hero_emergence'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['emergent'],
  },
  {
    tag: 'rebel',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks rebellious NPCs who lead splinter movements',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['rebellious', 'splinter'],
  },
  {
    tag: 'charismatic',
    category: 'trait',
    rarity: 'legendary',
    description: 'Marks charismatic leaders',
    usageCount: 1,
    templates: ['faction_splinter'],
    entityKinds: ['npc'],
    minUsage: 3,
  },

  // AFFILIATION TAGS
  {
    tag: 'criminal',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks NPCs involved in criminal activities',
    usageCount: 2,
    templates: ['outlaw_recruitment'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['recruit'],
  },
  {
    tag: 'family',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks members of extended family structures',
    usageCount: 2,
    templates: ['kinship_constellation'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['second_generation'],
  },
  {
    tag: 'orca',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks orca raiders and their combat techniques',
    usageCount: 2,
    templates: ['orca_raider_arrival', 'orca_combat_technique'],
    entityKinds: ['npc', 'abilities'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['raider', 'external-threat', 'predator'],
  },
  {
    tag: 'external-threat',
    category: 'affiliation',
    rarity: 'rare',
    description: 'Marks entities representing external threats',
    usageCount: 2,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['orca', 'raider', 'predator'],
  },
  {
    tag: 'guild',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks guild factions',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['trade', 'guild-founder', 'trader'],
  },
  {
    tag: 'cult',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks cult factions',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['cultist', 'prophet', 'mystical', 'secretive'],
  },
  {
    tag: 'cultist',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks cult followers',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['cult', 'prophet', 'mystic'],
  },
  {
    tag: 'external',
    category: 'affiliation',
    rarity: 'legendary',
    description: 'Marks techniques from external threats',
    usageCount: 1,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['orca', 'external-threat'],
  },

  // BEHAVIOR TAGS
  {
    tag: 'raider',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks raiding NPCs',
    usageCount: 1,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['orca', 'predator', 'external-threat'],
  },
  {
    tag: 'predator',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks predatory NPCs',
    usageCount: 1,
    templates: ['orca_raider_arrival'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['raider', 'orca', 'external-threat'],
  },
  {
    tag: 'trader',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks trader NPCs',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['guild', 'guild-founder', 'merchant'],
  },
  {
    tag: 'secretive',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks secretive factions',
    usageCount: 1,
    templates: ['cult_formation'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['cult', 'mystical'],
  },
  {
    tag: 'explorer',
    category: 'behavior',
    rarity: 'rare',
    description: 'Marks explorer NPCs who discover new locations',
    usageCount: 2,
    templates: ['krill_bloom_migration'],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 30,
  },
  {
    tag: 'merchant',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks merchant NPCs',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['npc'],
    minUsage: 3,
    relatedTags: ['trader'],
  },
  {
    tag: 'offensive',
    category: 'behavior',
    rarity: 'legendary',
    description: 'Marks offensive combat techniques',
    usageCount: 1,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['combat'],
  },

  // THEME TAGS
  {
    tag: 'mystery',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks locations or entities involved in mysterious disappearances',
    usageCount: 2,
    templates: ['mysterious_vanishing'],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 10,
    relatedTags: ['vanishing', 'mysterious', 'anomaly'],
  },
  {
    tag: 'vanishing',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks disappearance sites',
    usageCount: 1,
    templates: ['mysterious_vanishing'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['mystery'],
  },
  {
    tag: 'trade',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks trade-focused factions',
    usageCount: 1,
    templates: ['guild_establishment'],
    entityKinds: ['faction'],
    minUsage: 3,
    relatedTags: ['guild', 'trader', 'merchant'],
  },
  {
    tag: 'mystical',
    category: 'theme',
    rarity: 'uncommon',
    description: 'Marks mystical entities and locations',
    usageCount: 5,
    templates: ['cult_formation', 'anomaly_manifestation', 'magic_discovery'],
    entityKinds: ['faction', 'location', 'abilities', 'npc'],
    minUsage: 3,
    maxUsage: 35,
    relatedTags: ['magic', 'anomaly'],
  },
  {
    tag: 'colony',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks colony locations',
    usageCount: 1,
    templates: ['colony_founding'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['new'],
  },
  {
    tag: 'anomaly',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks anomalous locations',
    usageCount: 1,
    templates: ['anomaly_manifestation'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['mystical', 'mysterious', 'mystery'],
  },
  {
    tag: 'krill',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks krill-related resources and NPCs',
    usageCount: 3,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location', 'npc'],
    minUsage: 3,
    maxUsage: 35,
    relatedTags: ['bloom', 'resource'],
  },
  {
    tag: 'resource',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks resource-rich locations',
    usageCount: 1,
    templates: ['krill_bloom_migration'],
    entityKinds: ['location'],
    minUsage: 3,
    relatedTags: ['krill', 'bloom'],
  },
  {
    tag: 'magic',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks magical abilities',
    usageCount: 2,
    templates: ['magic_discovery'],
    entityKinds: ['abilities'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['mystical'],
    conflictingTags: ['technology', 'tech'],
  },
  {
    tag: 'technology',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks technological abilities',
    usageCount: 1,
    templates: ['tech_breakthrough'],
    entityKinds: ['abilities'],
    minUsage: 3,
    relatedTags: ['tech', 'innovation'],
    conflictingTags: ['magic', 'mystical'],
  },
  {
    tag: 'combat',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks combat-related abilities',
    usageCount: 2,
    templates: ['orca_combat_technique'],
    entityKinds: ['abilities'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['offensive'],
  },
  {
    tag: 'crisis',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks crisis-driven legislation',
    usageCount: 1,
    templates: ['crisis_legislation'],
    entityKinds: ['rules'],
    minUsage: 3,
  },
  {
    tag: 'festival',
    category: 'theme',
    rarity: 'rare',
    description: 'Marks festival celebrations',
    usageCount: 2,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['harvest', 'memorial', 'treaty', 'celestial'],
  },
  {
    tag: 'harvest',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks harvest festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'memorial',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks memorial festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'treaty',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks peace treaty festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'celestial',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks celestial celebration festivals',
    usageCount: 1,
    templates: ['great_festival'],
    entityKinds: ['rules'],
    minUsage: 3,
    relatedTags: ['festival'],
  },
  {
    tag: 'ideology',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks ideological movements',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
  },
  {
    tag: 'militarism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks militaristic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['pacifism'],
  },
  {
    tag: 'pacifism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks pacifist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['militarism'],
  },
  {
    tag: 'unity',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks unity-focused ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['isolation'],
  },
  {
    tag: 'isolation',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks isolationist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['unity'],
  },
  {
    tag: 'equality',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks equality-focused ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['hierarchy'],
  },
  {
    tag: 'tradition',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks traditionalist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['radical'],
  },
  {
    tag: 'hierarchy',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks hierarchical ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['equality'],
  },
  {
    tag: 'rationalism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks rationalist ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['mystical'],
  },
  {
    tag: 'asceticism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks ascetic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['hedonism'],
  },
  {
    tag: 'hedonism',
    category: 'theme',
    rarity: 'legendary',
    description: 'Marks hedonistic ideologies',
    usageCount: 1,
    templates: ['ideology_emergence'],
    entityKinds: ['rules'],
    minUsage: 3,
    conflictingTags: ['asceticism'],
  },

  // NEWLY ADDED TAGS (from tag analysis)
  {
    tag: 'exploration',
    category: 'behavior',
    rarity: 'common',
    description: 'Marks exploration-related activities and entities',
    usageCount: 0,
    templates: [],
    entityKinds: ['npc', 'location'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['explorer', 'discovery'],
  },
  {
    tag: 'neutral',
    category: 'affiliation',
    rarity: 'uncommon',
    description: 'Marks entities with no strong factional allegiance',
    usageCount: 0,
    templates: [],
    entityKinds: ['npc', 'faction', 'location'],
    minUsage: 3,
    maxUsage: 20,
  },
  {
    tag: 'virgin',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks untouched, pristine locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['unspoiled', 'hidden'],
  },
  {
    tag: 'food',
    category: 'theme',
    rarity: 'common',
    description: 'Marks food resources and related entities',
    usageCount: 0,
    templates: [],
    entityKinds: ['location', 'npc', 'abilities'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['krill', 'fishing', 'resource'],
  },
  {
    tag: 'fishing',
    category: 'behavior',
    rarity: 'common',
    description: 'Marks fishing-related activities and abilities',
    usageCount: 0,
    templates: [],
    entityKinds: ['npc', 'abilities', 'location'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['food', 'krill'],
  },
  {
    tag: 'hidden',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks concealed or secret locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['secretive', 'mystery', 'virgin'],
  },
  {
    tag: 'deep',
    category: 'location',
    rarity: 'common',
    description: 'Marks deep underwater locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['surface', 'depth'],
  },
  {
    tag: 'surface',
    category: 'location',
    rarity: 'common',
    description: 'Marks surface-level locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['deep'],
  },
  {
    tag: 'strategic',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks strategically important locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['defensive', 'vantage'],
  },
  {
    tag: 'defensive',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks defensible locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location', 'abilities'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['strategic', 'fortified'],
  },
  {
    tag: 'conflict',
    category: 'theme',
    rarity: 'uncommon',
    description: 'Marks conflict-related entities and events',
    usageCount: 0,
    templates: [],
    entityKinds: ['npc', 'faction', 'rules', 'location'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['combat', 'war'],
  },
  {
    tag: 'organized',
    category: 'trait',
    rarity: 'common',
    description: 'Marks organized, structured entities',
    usageCount: 0,
    templates: [],
    entityKinds: ['faction', 'npc', 'location'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['guild', 'hierarchy'],
  },
  {
    tag: 'glowing',
    category: 'trait',
    rarity: 'uncommon',
    description: 'Marks entities that emit light',
    usageCount: 0,
    templates: [],
    entityKinds: ['location', 'abilities'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['mystical', 'anomaly'],
  },
  {
    tag: 'windy',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks wind-swept locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['vantage'],
  },
  {
    tag: 'vantage',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks locations with excellent viewpoints',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['strategic', 'windy'],
  },
  {
    tag: 'icy',
    category: 'location',
    rarity: 'common',
    description: 'Marks ice-based locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 30,
  },
  {
    tag: 'landmark',
    category: 'location',
    rarity: 'uncommon',
    description: 'Marks notable landmark locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 20,
    relatedTags: ['recognized', 'prominent'],
  },
  {
    tag: 'multilevel',
    category: 'location',
    rarity: 'rare',
    description: 'Marks multi-tiered locations',
    usageCount: 0,
    templates: [],
    entityKinds: ['location'],
    minUsage: 3,
    maxUsage: 10,
  },
  {
    tag: 'leader',
    category: 'status',
    rarity: 'uncommon',
    description: 'Marks leadership NPCs',
    usageCount: 0,
    templates: [],
    entityKinds: ['npc'],
    minUsage: 3,
    maxUsage: 25,
    relatedTags: ['charismatic', 'organized'],
  },
  {
    tag: 'cultural',
    category: 'theme',
    rarity: 'common',
    description: 'Marks culturally significant entities',
    usageCount: 0,
    templates: [],
    entityKinds: ['rules', 'abilities', 'location'],
    minUsage: 3,
    maxUsage: 30,
    relatedTags: ['festival', 'ideology', 'tradition'],
  },
  {
    tag: 'emergency',
    category: 'theme',
    rarity: 'uncommon',
    description: 'Marks emergency measures and crisis responses',
    usageCount: 0,
    templates: [],
    entityKinds: ['rules'],
    minUsage: 3,
    maxUsage: 15,
    relatedTags: ['crisis'],
  },
];
